
CREATE DATABASE IF NOT EXISTS CITI default char set utf8;

USE CITI;
/**
 * CITI_RATEDATA
 * RD_ID 表字段ID 主键
 * RD_CODE 数据来源码
 * RD_STOCKINDEX 股票指数
 * RD_STOCKDATE 股指发布时间
 */
CREATE TABLE CITI_RateData(
	RD_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	RD_STOCKINDEX DOUBLE NOT NULL,
	RD_STOCKDATE DATETIME NOT NULL,
	PRIMARY KEY(RD_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
--测试SQL语句
insert into CITI_RateData value(null,'01',1.01,now());
/**
 * 查询后50条数据
 */
select * from CITI_RATEDATA order by RD_STOCKDATE desc limit 50;


CREATE TABLE CITI_StanData (
	SD_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	SD_DEPO_RATE DOUBLE NOT NULL,
	SD_CRED_RATE DOUBLE NOT NULL,
	SD_PROD_RATE DOUBLE NOT NULL,
	SD_PROD_DLINE DOUBLE NOT NULL,
	SD_MORT_RATE DOUBLE NOT NULL,
	SD_MOTR_DLINE DOUBLE NOT NULL,
	PRIMARY KEY(SD_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE CITI_USERINFO (
	UI_INFOID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	UI_BANKID CHAR(16) NOT NULL,
	UI_NAME CHAR(15) NOT NULL,
	UI_ID CHAR(18) NOT NULL,
	UI_PASSW CHAR(128) NOT NULL,
	PRIMARY KEY(UI_INFOID),
	INDEX(UI_INFOID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into CITI_USERINFO value(null,'8888888888888888','admin','230229198709250035','admin');
insert into CITI_USERINFO value(null,'4392257113389120','李云鹏','230229198709250035','123');
update CITI_USERINFO set UI_PASSW = '356a192b7913b04c54574d18c28d46e6395428ab' where ui_bankid = '4392257113389120';

CREATE TABLE CITI_PURC_ACCOUNT (
	PA_INFOID INT UNSIGNED NOT NULL,
	PA_PURC_FUND DOUBLE NOT NULL,
	PRIMARY KEY(PA_INFOID),
	FOREIGN KEY(PA_INFOID) REFERENCES CITI_USERINFO(UI_INFOID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CITI_USERINFO_ADD (
	UA_INFOID INT UNSIGNED NOT NULL,
	UA_AVG_MICOM DOUBLE,
	UA_AVG_MPOUT DOUBLE,
	PRIMARY KEY(UA_INFOID),
	FOREIGN KEY(UA_INFOID) REFERENCES CITI_USERINFO(UI_INFOID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into CITI_USERINFO_ADD(UA_INFOID,UA_AVG_MICOM,UA_AVG_MPOUT) values(2,6500,1600) on duplicate key update UA_INFOID = 2,UA_AVG_MICOM = 6500 ,UA_AVG_MPOUT = 1700;

CREATE TABLE CITI_ACCOUNT_FUNDS (
	AF_INFOID INT UNSIGNED NOT NULL,
	AF_FUNDS DOUBLE,
	PRIMARY KEY(AF_INFOID),
	FOREIGN KEY(AF_INFOID) REFERENCES CITI_USERINFO(UI_INFOID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CITI_PURC_PROG (
	PP_INFOID INT UNSIGNED NOT NULL,
/*	PP_ID TINYINT UNSIGNED NOT NULL, */
	pp_DPAY INT NOT NULL,
	PP_MFUND DOUBLE NOT NULL,
	PP_MCOUNT TINYINT NOT NULL,
	PP_PURC_DATE DATE NOT NULL,
	PP_SQUARYM INT NOT NULL,
	PP_MPRICE DOUBLE NOT NULL,
	PP_FUNDS DOUBLE NOT NULL,
	PRIMARY KEY(PP_INFOID),
	FOREIGN KEY(PP_INFOID) REFERENCES CITI_USERINFO(UI_INFOID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE CITI_USER_NOTE (
	UN_INFOID INT UNSIGNED NOT NULL,
	UN_NOTE TEXT NOT NULL,
	UN_UPDATADATE DATE NOT NULL,
	NDATE DATE NOT NULL,
	PRIMARY KEY(UN_INFOID),
	FOREIGN KEY(UN_INFOID) REFERENCES CITI_USERINFO(UI_INFOID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CITI_INVE_PREF (
	IP_INFOID INT UNSIGNED NOT NULL,
	IP_PREF TINYINT NOT NULL,
	PRIMARY KEY(IP_INFOID),
	FOREIGN KEY(IP_INFOID) REFERENCES CITI_USERINFO(UI_INFOID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;